name: mgg_packgen
description: "MGG-Packify – Portal Retail Skandia México"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  http: ^1.2.0
  go_router: ^14.0.0
  file_picker: ^8.0.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.0
  shared_preferences: ^2.3.0
  local_notifier: ^0.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
